repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.13.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]

  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black
        args: ["--target-version", "py36"]
        # override until resolved: https://github.com/psf/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-2020, flake8-implicit-str-concat]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: update-readme
        name: Update README
        entry: python3 generate_readme.py
        language: system
        pass_filenames: false
        files: ^(generate_readme\.py)|(images\/.*png)$
