language: python
sudo: false
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U black flake8
 - pip install -U -r requirements.txt


script:
 # Static analysis
 - flake8 .
 - black --check --diff .

 # Test run
 - python pypi-trends.py --dry-run
 - python jsons2csv.py
 - python macos-versions.py -i data/macos-2018-09-15.json
