language: python
sudo: false
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5

install:
 - pip install flake8
 - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install black; fi
 - pip install -r requirements.txt


script:
 # Static analysis
 - flake8 .
 - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black --check --diff .; fi

 # Test run
 - python pypi-trends.py --dry-run
 - python jsons2csv.py
 - python macos-versions.py -i data/macos-2018-09-15.json
