language: python
sudo: false
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - "3.6"
 - "3.5"

install:
 - pip install flake8
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi
 - pip install -r requirements.txt


script:
 # Static analysis
 - flake8 .
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi

 # Test run
 - python pypi-trends.py --dry-run
 - python jsons2csv.py
 - python macos-versions.py -i data/macos-2018-09-15.json

matrix:
  fast_finish: true
