language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9-dev

install:
 - pip install -U pip
 - pip install -U pre-commit pytest
 - pip install -U -r requirements.txt

script:
  # Static analysis
  - pre-commit run --all-files

  # Unit tests
  - python -m pytest

  # Fetch fresh copy of top packages
  - wget https://hugovk.github.io/top-pypi-packages/top-pypi-packages-30-days.min.json -O data/top-pypi-packages.json

  # Test run
  - python pypi-trends.py --dry-run
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.9-dev" ]; then python jsons2csv.py ; fi
  - make -j4
  - python generate_readme.py
  - python macos-versions.py -i macos.json
  - python project_urls.py -n 1
