[tool.black]
py36 = true

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = ["dateutil", "natsort", "pytablewriter", "termcolor"]
line_length = 88
multi_line_output = 3
use_parentheses = true
