[tool.black]
target_version = ["py36"]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = ["appdirs", "dateutil", "httpx", "natsort", "packaging", "pypidb", "pytablewriter", "pytest", "pytz", "requests", "slugify", "termcolor"]
line_length = 88
multi_line_output = 3
use_parentheses = true
