name: Test

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -U pre-commit pytest
          python -m pip install -U -r requirements.txt

      - name: Unit tests
        shell: bash
        run: |
          python -m pytest

      - name: Fetch fresh copy of top packages
        shell: bash
        run: |
          wget https://hugovk.github.io/top-pypi-packages/top-pypi-packages-30-days.min.json -O data/top-pypi-packages.json

      - name: Test run
        shell: bash
        run: |
          python pypi-trends.py --dry-run
          python jsons2csv.py
          make -j4
          python generate_readme.py
          python macos-versions.py -i macos.json
          python project_urls.py -n 1
